# Generated by Django 4.2 on 2024-09-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription_test',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
