# Generated by Django 4.2 on 2024-09-17 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='like',
            name='content_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('comment', 'Comment')], default='article', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('content_type', 'content_id', 'user')},
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['content_type', 'content_id'], name='articles_li_content_ba033e_idx'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='article',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked_at',
        ),
    ]
