# Generated by Django 4.2 on 2024-09-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_like_unique_together_like_content_id_and_more'),
        ('articles', '0003_article_image'),
    ]

    operations = [
    ]
